### ISSUE TITLE
AP exposes file system on root handler

### ISSUE THREAD

**Issue by oscarlomas09** [tripflex/wifi-captive-portal#9]
I don't know if this is an issue with the captive portal or with mongoose os itself, but upon creating the device portal and it creating an access point, it exposes the file system.

So once you connect to the device and visit 192.168.4.1 it show this 
![exposed](https://user-images.githubusercontent.com/11875042/47936616-76d88a80-de9b-11e8-92f1-23ee0cd271bf.JPG)

I could then click on each individual file and see its code. Is there any way to disable this?

**Comment by marciopamplona** [comment]
This happens when the hostname (portal.wifi.hostname) is not in the localgroup. Try add the ".local" in hostname. The default hostname is 'setup.device.local'.

**Comment by tripflex** [comment]
@oscarlomas09 yes by encrypting the device before releasing to anybody ... 

Are you by chance using a Samsung device for this?  What I found is that Samsung devices for some weird ass reason do not seem to support GZIP files ... figured it out the other day when testing on a friends new samsung device when it would not work with captive portal .. but when i disabled gzip it worked ... UGHHHHH

**Comment by tripflex** [comment]
So i believe this is due to incompatibility of serving a non `index.html` file ... seems to be a problem with using this line of code:
https://github.com/tripflex/wifi-captive-portal/blob/master/src/mgos_wifi_captive_portal.c#L229-L231

Which IMO may be related to an issue on the client/user device, as it works fine for me on some devices, on others (like Samsung Android devices), it does not.  In my separation of this lib into pieces, i think i'm going to just use an `index.html` file as default and allow users to customize that if they want, in the instance they are using their own custom index file or something

**Comment by tripflex** [comment]
@marciopamplona @oscarlomas09 Please use the new library:

https://github.com/tripflex/captive-portal-wifi-stack

IS a combination of all of these libs:
https://github.com/tripflex/captive-portal
https://github.com/tripflex/captive-portal-wifi-setup
https://github.com/tripflex/captive-portal-wifi-rpc
https://github.com/tripflex/captive-portal-wifi-web
